import Head from 'next/head'
import styles from '../styles/Home.module.css'
import TailwindPractice from "../components/TailwindPractice"
export default function Home() {
  return (
    <div>
      <Head>
        <title>Space-X</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TailwindPractice />

    </div>
  )
}
